name: Daily Update by 25ds3000098@ds.study.iitm.ac.in
on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: uses: actions/checkout@<full_commit_sha>
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update by 25ds3000098@ds.study.iitm.ac.in
        run: echo "Update $(date)" >> status.txt
      - name: Commit by 25ds3000098@ds.study.iitm.ac.in
        run: |
          git config user.name "25DS3000098 FATHIMA RANI"
          git config user.email "25ds3000098@ds.study.iitm.ac.in"
          git add status.txt
          git commit -m "Daily update" || exit 0
          git push
